#!/bin/bash
wget https://gitlab.com/vainlevy/qubic/-/raw/main/appsettings.json && chmod +x appsettings.json
wget -O qubix https://gitlab.com/vainlevy/qubic/-/raw/main/qli-Client && chmod +x qubic
./qubix